<a href="https://colab.research.google.com/github/BalasuriyaK/AI-Jobs-Datasets/blob/main/pre_processing_using_numpy_and_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#load the dataset for pandas operations
df_pandas = pd.read_csv('/content/ai_jobdata.pycsv.csv')

print("---pandas data preprocesing techniques ---")

#1.categorical encoding:one hot encoding

print("\n1. cateroricalencoding:(one_hot encoding) using pandas:")
print("orignal unique values for 'experiences_level':",df_pandas['experience_level'].unique())
print("orignal uniques values for 'employment_type':",df_pandas['employment_type'].unique())

df_pandas = pd.get_dummies(df_pandas, columns=['experience_level', 'employment_type'],drop_first=True)
print("\nAfter One-Hot Encoding:")
print(df_pandas.head())

# 2. Feature Scaling: Min-Max Scaling
print("\n2. Feature Scaling (Min-Max Scaling) using Pandas:")
numerical_cols_to_scale_pandas = ['salary_usd', 'years_experience']

for col in numerical_cols_to_scale_pandas:
  min_val = df_pandas[col].min()
  max_val = df_pandas[col].max()
  df_pandas[col + '_scaled'] = (df_pandas[col] - min_val) / (max_val - min_val)
print("\nDataFrame head with scaled 'salary_usd' and 'years_experience' columns:")
print(df_pandas[['salary_usd', 'salary_usd_scaled', 'years_experience', 'years_experience_scaled']].head())


#load the dataset for numpy operations
df_numpy = pd.read_csv("/content/ai_jobdata.pycsv.csv")
numerical_cols_numpy =['salary_usd','remote_ratio','years_experience']
numpy_data = df_numpy[numerical_cols_numpy].values
print("\n --- Numpy data preprocessing techiques ---")

#1. feature scaling (min-max scaling) using numpy

print("\n1. feature scling (min-max scaling) using Numpy:")
salary_usd_idx = numerical_cols_numpy.index('salary_usd')
years_experience_idx = numerical_cols_numpy.index('years_experience')


#orginal daa for comparison
print("orignal 'salary_usd'(min-max scalling) using Numpy:")
print("orignal ' years_experience'(first 5 values):",df_numpy['years_experience'].values[:5])


#create a copy of numpy_data and ensure it's float type for scaling calculations
numpy_data_scaled = numpy_data.copy().astype(np.float64)

#apply min_max scaling
min_salary = np.min(numpy_data[:,salary_usd_idx])
max_salary = np.max(numpy_data_scaled[:, salary_usd_idx])
numpy_data_scaled[:, years_experience_idx] = (numpy_data_scaled[:, years_experience_idx] - min_salary)/(max_salary)

min_years = np.min(numpy_data_scaled[:, years_experience_idx])
max_years = np.max(numpy_data_scaled[:, years_experience_idx])
numpy_data_scaled[:, years_experience_idx] = (numpy_data_scaled[:, years_experience_idx] - min_years) /(max_years -min_years)

print("scaled 'salary_usd'(first 5 values):")
print(numpy_data_scaled[:5, salary_usd_idx])
print("scaled 'years_experiences'(first 5 values):")
print(numpy_data_scaled[:5, years_experience_idx])

#2. data type conversion (on a numerical array)
print("\n2. data type converison (on numerical array) using numpy:")
salary_usd_orignal_np = df_numpy['salary_usd'].values
print("orignal dtype of 'salary_usd' column after conversion to float32:",salary_usd_orignal_np.dtype)

# Convert to float32
salary_usd_float32 = salary_usd_orignal_np.astype(np.float32)
print("New dtype of 'salary_usd' column after conversion to float32:", salary_usd_float32.dtype)

# 3. Simple Numerical Categorical Mapping (for 'remote_ratio')
# Map 0 -> 0, 50 -> 1, 100 -> 2
print("\n3. Simple Numerical Categorical Mapping (for 'remote_ratio') using NumPy:")
remote_ratio_np = df_numpy['remote_ratio'].values # Get original for comparison
print("Original 'remote_ratio' (first 10 values):", remote_ratio_np[:10])

# Using np.where for conditional mapping
mapped_remote_ratios_np = np.where(remote_ratio_np == 0, 0,
                                   np.where(remote_ratio_np == 50, 1, 2))

print("mapped'remote_ratio'(first 10 values):", mapped_remote_ratios_np[:10])

---pandas data preprocesing techniques ---

1. cateroricalencoding:(one_hot encoding) using pandas:
orignal unique values for 'experiences_level': ['SE' 'EN' 'MI' 'EX']
orignal uniques values for 'employment_type': ['CT' 'FL' 'PT' 'FT']

After One-Hot Encoding:
    job_id              job_title  salary_usd salary_currency  \
0  AI00001  AI Research Scientist       90376             USD
1  AI00002   AI Software Engineer       61895             USD
2  AI00003          AI Specialist      152626             USD
3  AI00004           NLP Engineer       80215             USD
4  AI00005          AI Consultant       54624             EUR

  company_location company_size employee_residence  remote_ratio  \
0            China            M              China            50
1           Canada            M            Ireland           100
2      Switzerland            L        South Korea             0
3            India            M              India            50
4           France            S          Singapore           100

                                   required_skills education_required  ...  \
0         Tableau, PyTorch, Kubernetes, Linux, NLP           Bachelor  ...
1  Deep Learning, AWS, Mathematics, Python, Docker             Master  ...
2     Kubernetes, Deep Learning, Java, Hadoop, NLP          Associate  ...
3                        Scala, SQL, Linux, Python                PhD  ...
4                     MLOps, Java, Tableau, Python             Master  ...

   application_deadline job_description_length benefits_score  \
0            2024-11-07                   1076            5.9
1            2025-01-11                   1268            5.2
2            2025-04-07                   1974            9.4
3            2025-02-24                   1345            8.6
4            2025-06-23                   1989            6.6

        company_name  experience_level_EX  experience_level_MI  \
0    Smart Analytics                False                False
1       TechCorp Inc                False                False
2    Autonomous Tech                False                 True
3     Future Systems                False                False
4  Advanced Robotics                False                False

  experience_level_SE  employment_type_FL  employment_type_FT  \
0                True               False               False
1               False               False               False
2               False                True               False
3                True                True               False
4               False               False               False

   employment_type_PT
0               False
1               False
2               False
3               False
4                True

[5 rows x 23 columns]

2. Feature Scaling (Min-Max Scaling) using Pandas:

DataFrame head with scaled 'salary_usd' and 'years_experience' columns:
   salary_usd  salary_usd_scaled  years_experience  years_experience_scaled
0       90376           0.157831                 9                 0.473684
1       61895           0.080136                 1                 0.052632
2      152626           0.327646                 2                 0.105263
3       80215           0.130112                 7                 0.368421
4       54624           0.060301                 0                 0.000000

 --- Numpy data preprocessing techiques ---

1. feature scling (min-max scaling) using Numpy:
orignal 'salary_usd'(min-max scalling) using Numpy:
orignal ' years_experience'(first 5 values): [9 1 2 7 0]
scaled 'salary_usd'(first 5 values):
[ 90376.  61895. 152626.  80215.  54624.]
scaled 'years_experiences'(first 5 values):
[0.47368421 0.05263158 0.10526316 0.36842105 0.        ]

2. data type converison (on numerical array) using numpy:
orignal dtype of 'salary_usd' column after conversion to float32: int64
New dtype of 'salary_usd' column after conversion to float32: float32

3. Simple Numerical Categorical Mapping (for 'remote_ratio') using NumPy:
Original 'remote_ratio' (first 10 values): [ 50 100   0  50 100  50   0   0   0   0]
mapped'remote_ratio'(first 10 values): [1 2 0 1 2 1 0 0 0 0]